# Jupyter Notebooks
Jupyter Notebooks are web applications that lets us combine pieces of executable code, text, images, and visualizations in a single document, or notebook. We have installed a Jupyter Extension that lets us run notebooks directly in Visual Studio Code (VS Code).

Sections of a notebook are called cells. Cells can be run independently of each other, and in any order.

## Adding text

Notebooks use markdown, a markup language, for formatting text. IBM publishes a [Jupyter-specific markdown cheat sheet](https://www.ibm.com/docs/en/watson-studio-local/1.2.3?topic=notebooks-markdown-jupyter-cheatsheet).

To add a text cell:
1. Click **+ Markdown**
2. Add some text. When you are done editing, press `ctrl` + `enter` to run the cell and format your text.

To use VS Code with the Jupyter extension for writing and running code, follow these modified steps:

## Writing and Running Code in VS Code with Jupyter Extension

1. **Writing Code Cells:**
   - Use code cells to write your Python code. To create a new code cell, click on the `+ Code` button in the Jupyter toolbar.
   - Type or paste your Python code within the code cell.

2. **Running Code Cells:**
   - To execute a code cell, you can:
     - Click the `Run Cell` button (a triangle icon) in the Jupyter toolbar.
     - Use the keyboard shortcut `Shift + Enter`.
   - Output, if any, will be displayed below the cell after execution.

3. **Keyboard Shortcuts:**
   - Utilize keyboard shortcuts for faster execution:
     - `Shift + Enter`: Run the current cell and move to the next cell.
     - `Ctrl + Enter`: Run the current cell and stay on the same cell.
     - `Alt + Enter`: Run the current cell and insert a new cell below.

4. **Code Assistance and Auto-completion:**
   - The Jupyter extension in VS Code offers code assistance and auto-completion. Press `Tab` for suggestions while writing code.

5. **Saving and Renaming:**
   - Save your Jupyter notebook by clicking on `File` > `Save` or `File` > `Save As...`.
   - To rename the notebook, right-click on the notebook file in the file explorer on the left and select `Rename`.

6. **Managing Cells:**
   - Use the `+ Code` or `+ Markdown` buttons in the Jupyter toolbar to add new code or text cells, respectively.
   - You can rearrange the order of cells by clicking and dragging them in the Jupyter notebook.
   - Right-click on a cell in the Jupyter notebook to access options like deleting or moving the cell.

No problem! If you won't be using Google Colab or Drive, and you want to work exclusively in Visual Studio Code, here are modified instructions:

## Instructions for Accessing and Using the `data` Folder in Visual Studio Code

1. **Access GitHub Repository:**
   - Go to your GitHub repository where the `data` folder is located: [https://github.com/UofT-DSI/python](https://github.com/UofT-DSI/python)
   - Clone the repository to your local machine using the following command in your terminal or command prompt:
     ```
     git clone https://github.com/UofT-DSI/python.git
     ```
   - Navigate to the cloned repository on your local machine.

2. **Access and Use the `data` Folder in Visual Studio Code:**
   - Open Visual Studio Code.
   - Open the folder corresponding to the cloned GitHub repository using the "File" > "Open Folder..." menu option.
   - You should now see the `data` folder in your Visual Studio Code workspace.

3. **Working with the `data` Folder:**
   - You can access and use the contents of the `data` folder directly in your Python scripts or Jupyter notebooks within Visual Studio Code. For example, you can read data from files in the `data` folder using Python's file handling functions or libraries like Pandas.

### What is Python?

Python is a general-purpose programming language first released in 1991. It has since become a popular language for data science, thanks to an enthusiastic community and a large ecosystem of code libraries and tools that make it easier to perform common tasks throughout the data science life cycle.

In [ ]:
50 > 25

In [ ]:
50 == 50

In [ ]:
20 != 23

In [ ]:
print(True + 1)

In [39]:
Degree_celsius = 20
degree_celsius = 30

"""

30_april_2024-live_coding.ipynb
block comment

"""



'\n\n30_april_2024-live_coding.ipynb\nblock comment\n\n'

#HEading

In [68]:
print(degree_celsius)

a = 10

list1 = [1,2,3]
print(id(list1))
list2 = list1
print(id(list2))
list1 = [1,2,3,4]
print(id(list1))
print(id(list2))

dsi = "Monday"
type(int("3"))

print(type(round(2*1.5)))

def my_function(a: int, b: float = 188.3) -> float:
    '''Convert input to string'''
    return "Str,"+str(a)+","+str(int(round(b)))

my_function(1)
#help(my_function)


30
2275263103360
2275263103360
2275263653376
2275263103360
<class 'int'>


'Str,1,188'

In [70]:
print(True and "Anjali")
print("Anjali" and True)

Anjali
True


In [83]:
print("Anjali" and True)
print(1 and True)

True
True


In [30]:
str = "Anjali"
# list
vowels = ["a","e","i","o","u"]
print("{} are vowels".format(vowels))
print(f"{vowels} are vowels")

# best practice to create empty list instead of empty_list = list()
empty_list = []
print("empty list is", type(empty_list))

grades = ['k',1,2,3,4]
summary_functions = [len, sum, max, min]

mystery_solvers = [['Sherlock','Watson'],
                   ['Scooby','Shaggy', 'Fred','Velma','Daphe'],
                   'Nancy'
                   ]

print(grades[0:3])
print(grades[-4:])

'e' in vowels


['a', 'e', 'i', 'o', 'u'] are vowels
['a', 'e', 'i', 'o', 'u'] are vowels
empty list is <class 'list'>
['k', 1, 2]
[1, 2, 3, 4]


True

In [31]:
# strings are immutable
emma = "cheese sandwich"
kaylie = emma
print(emma)
print(kaylie)
print(id(emma))
print(id(kaylie))
emma = "ham sandwich"
print(emma)
print(kaylie)
print(id(emma))
print(id(kaylie))

cheese sandwich
cheese sandwich
3111196079856
3111196079856
ham sandwich
cheese sandwich
3111196078576
3111196079856


In [18]:
# lists are mutable
sandwich = ['bread', 'cheese', 'bread']
sandwich_copy = sandwich

sandwich[0]='ham'
print(sandwich)
print(sandwich_copy)
print(id(sandwich))
print(id(sandwich_copy))

['ham', 'cheese', 'bread']
['ham', 'cheese', 'bread']
3111195701120
3111195701120


In [25]:
combo=['burger', 'fries', 'drink']
kid_meal=list(combo)
print(combo)
print(kid_meal)
kid_meal[0]='chicken_sandwich'
print(combo)
print(kid_meal)

letters = ['a','b','c']
print(len(letters))

['burger', 'fries', 'drink']
['burger', 'fries', 'drink']
['burger', 'fries', 'drink']
['chicken_sandwich', 'fries', 'drink']
3


In [26]:
# most functions will not change the value
# most methods will mutate them or change them
rainbow = ['red', 'orange']
# append is used to add single element to the end of list
rainbow.append('purple')
rainbow

['red', 'orange', 'purple']

In [28]:
rainbow.append(['blue', 'green'])
rainbow

['red', 'orange', 'purple', ['blue', 'green']]

In [29]:
rainbow.extend('red')
rainbow

['red', 'orange', 'purple', ['blue', 'green'], 'r', 'e', 'd']

In [33]:
fruits=['pineapple', 'apple','kiwi','banana']
fruits.sort()
fruits

['apple', 'banana', 'kiwi', 'pineapple']

In [40]:
fruits=['pineapple', 'apple', 'kiwi', 'banana', 'orange']
print(sorted(fruits))
print(fruits)

['apple', 'banana', 'kiwi', 'orange', 'pineapple']
['pineapple', 'apple', 'kiwi', 'banana', 'orange']


In [1]:
fruits=['pineapple', 'apple','kiwi','banana']
def last_letter(text):
    return text[-1]

print(sorted(fruits, key=last_letter))
print(fruits)

['banana', 'pineapple', 'apple', 'kiwi']
['pineapple', 'apple', 'kiwi', 'banana']


In [3]:
students_per_class = [['Grade 9', 25], ['Grade 8', 22],
                        ['Grade 7', 24]]
def second_element(item):
    return item[1]

students_per_class.sort(key=second_element)
students_per_class

[['Grade 8', 22], ['Grade 7', 24], ['Grade 9', 25]]

In [4]:
# Tuples are immutable: they cannot be chanhged once they are created.
mutable_synonyms = ('changeable', 'fluctuating', 'inconstant', 'variable');
mutable_synonyms

('changeable', 'fluctuating', 'inconstant', 'variable')

In [5]:
empty = ()
type(empty)

tuple

In [8]:
print(len(empty))
print(len(mutable_synonyms))
sorted(mutable_synonyms)

0
4


['changeable', 'fluctuating', 'inconstant', 'variable']

In [9]:
mutable_synonyms + ('modifiable', 'shifting')
print(mutable_synonyms)

('changeable', 'fluctuating', 'inconstant', 'variable')


In [26]:
# sets mutable, unordered and distinct (unique members)

things = {'coat', 'lock', 'book', 'xylophone', 'apple', 'box', 'box', 'book', 'lock'} 
print(things)


{'coat', 'apple', 'box', 'xylophone', 'lock', 'book'}


In [20]:
visitor_post_codes = ['M5R', 'M5V', 'M1M', 'M1M', 'M1T']
print(id(visitor_post_codes))
new_set = set(visitor_post_codes)
print(id(new_set))
new_set

2732201945152
2732203599680


{'M1M', 'M1T', 'M5R', 'M5V'}

In [16]:
empty_set = set() # not {}
print(empty_set)

set()


In [21]:
'lock' in things

True

In [22]:
things.add('lock')
things

{'apple', 'book', 'box', 'coat', 'lock', 'xylophone'}

In [23]:
things.add('mirror')
things

{'apple', 'book', 'box', 'coat', 'lock', 'mirror', 'xylophone'}

In [27]:
clone = things
print(clone)
things.remove('apple')
print(things)
print(clone)

{'coat', 'apple', 'box', 'xylophone', 'lock', 'book'}
{'coat', 'box', 'xylophone', 'lock', 'book'}
{'coat', 'box', 'xylophone', 'lock', 'book'}


In [28]:
# union, intersection, symmetric difference, difference

olympic_flag = {'red', 'green', 'yellow', 'blue', 'black'}
rainbow = {'red', 'orange', 'yellow', 'green', 'blue', 'indigo', 'violet'}
rainbow.difference(olympic_flag)


{'indigo', 'orange', 'violet'}

In [29]:
olympic_flag.difference(rainbow)

{'black'}

In [30]:
rainbow.symmetric_difference(olympic_flag)

{'black', 'indigo', 'orange', 'violet'}

In [31]:
rainbow.intersection(olympic_flag)


{'blue', 'green', 'red', 'yellow'}

In [32]:
rainbow.union(olympic_flag)

{'black', 'blue', 'green', 'indigo', 'orange', 'red', 'violet', 'yellow'}

In [8]:
# dictionaries store values in key value pairs
# they are mutable. every key is unique
# keys are immutable data type. Value can be mutable or immutable
capitals = {'Canada':'Ottawa',
            'United States': 'Washington, D.C.',
            'Mexico': 'Mexico City'}

olympic_cities = {2020: 'Tokyo',
                 2016: 'Rio de Janiero',
                 2012: 'London'}

print(olympic_cities)

{2020: 'Tokyo', 2016: 'Rio de Janiero', 2012: 'London'}


In [9]:
all_olympic_host = { 'summer': olympic_cities,
                     'winter': {2022:'Beijing', 2018: 'Pyeongchang'}}
print(all_olympic_host)

{'summer': {2020: 'Tokyo', 2016: 'Rio de Janiero', 2012: 'London'}, 'winter': {2022: 'Beijing', 2018: 'Pyeongchang'}}


In [38]:
empty_dictionary = {} # better to use this than empty_dictionary = dict()
type(empty_dictionary)

dict

In [54]:
olympic_cities[2012]

'London'

In [40]:
all_olympic_host['winter']

{2022: 'Beijing', 2018: 'Pyeongchang'}

In [41]:
all_olympic_host['winter'][2022]

'Beijing'

In [55]:
all_olympic_host['summer'][2020]

'Tokyo'

In [44]:
olympic_cities.get(2004, 'Not Found')

'Not Found'

In [46]:
all_olympic_host.get('winter',  'Not Found')

{2022: 'Beijing', 2018: 'Pyeongchang'}

In [63]:
olympic_cities[2008] = 'Beijing'
olympic_cities

{2016: 'Rio de Janiero', 2012: 'London', 2008: 'Beijing'}

In [10]:
all_olympic_host

{'summer': {2020: 'Tokyo', 2016: 'Rio de Janiero', 2012: 'London'},
 'winter': {2022: 'Beijing', 2018: 'Pyeongchang'}}

In [67]:
del olympic_cities[2020]
olympic_cities

{2016: 'Rio de Janiero', 2012: 'London'}

In [68]:
if 'London' in olympic_cities.values():
    print('London was a host city')
else:
    print('London was not a host city')

London was a host city


In [69]:
olympic_cities.items()

dict_items([(2016, 'Rio de Janiero'), (2012, 'London')])

In [3]:
# for loops
vowels = ['a', 'e', 'i', 'o', 'u']
for i in vowels:
    print(i)
    
for i in range(len(vowels)):
    print(i)

a
e
i
o
u
0
1
2
3
4


In [12]:
for key in all_olympic_host.keys():
    print(key)
    print(all_olympic_host[key])

summer
{2020: 'Tokyo', 2016: 'Rio de Janiero', 2012: 'London'}
winter
{2022: 'Beijing', 2018: 'Pyeongchang'}


In [14]:
input_files = ['data_01.csv', 'data_02.csv', 'data_03.csv', 'data_04.csv']
output_files = []
for i in input_files:
    output_filename = 'processed_' +  i.replace('.csv', '.xslsx')
    output_files.append(output_filename)

output_files

['processed_data_01.xslsx',
 'processed_data_02.xslsx',
 'processed_data_03.xslsx',
 'processed_data_04.xslsx']

In [16]:
veggies = {'carrots', 'celery', 'potatoes', 'tomatoes'}
for i in veggies:
    print(f'I love {i}')


I love potatoes
I love tomatoes
I love celery
I love carrots


In [19]:
ttc_stops = ['Islington', 'Royal York', 'Keele', 'Jane', 'Union']
for i, stop in enumerate(ttc_stops):
    #print(i, stop)
    print(f'Stop {i+1} {stop}')

Stop 1 Islington
Stop 2 Royal York
Stop 3 Keele
Stop 4 Jane
Stop 5 Union


In [22]:
for i, val in enumerate([1, 10, 100, 1000]):
    print(i, val)

0 1
1 10
2 100
3 1000


In [28]:
lats = (43.12, 24.56, 8.99)
lons = (0.332, 8.3, 43.22)
for i, j in zip(lats, lons):
    print(i, j)

43.12 0.332
24.56 8.3
8.99 43.22


In [29]:
for key, value in olympic_cities.items():
    print(key, value)

2020 Tokyo
2016 Rio de Janiero
2012 London


In [30]:
days = [12, 30, 17, 6, 7]
months = ['apr', 'may', 'june', 'jan', ]
for i in days:
    for j in months:
        print(f'My birthday is on {j}, {i}!')

My birthday is on apr, 12
My birthday is on may, 12
My birthday is on june, 12
My birthday is on jan, 12
My birthday is on apr, 30
My birthday is on may, 30
My birthday is on june, 30
My birthday is on jan, 30
My birthday is on apr, 17
My birthday is on may, 17
My birthday is on june, 17
My birthday is on jan, 17
My birthday is on apr, 6
My birthday is on may, 6
My birthday is on june, 6
My birthday is on jan, 6
My birthday is on apr, 7
My birthday is on may, 7
My birthday is on june, 7
My birthday is on jan, 7


In [33]:
# while loop
countdown = 4
while countdown > 0:
    print(countdown)
    countdown -= 1

4
3
2
1


In [36]:
countdown = 4
while countdown >0:
    print(countdown)
    if countdown == 3:
        break
    countdown -= 1

4
3


In [38]:
while True:
    password = input("Enter the password: ")
    if password.lower() == 'open sesame':
        print("You are in")
        break

You are in


In [40]:
wishes = 3
while wishes > 0:
    wish = input("Make a wish: ")
    if 'infinite wishes'  in wish.lower():
        print('You can\'t do that')
        continue
    else:
        print('Wish granted')
    wishes -= 1
print ('you have used all your wishes')


You can't do that
Wish granted
Wish granted
Wish granted
you have used all your wishes


In [48]:
# read()
# readline()
# readlines()

with open('../../05_data/slides_data/california_housing_test.csv', 'r') as filehandle:
    #print(filehandle)
    for i in range(5):
        print(filehandle.readline())
print(filehandle)

"longitude","latitude","housing_median_age","total_rooms","total_bedrooms","population","households","median_income","median_house_value"

-122.050000,37.370000,27.000000,3885.000000,661.000000,1537.000000,606.000000,6.608500,344700.000000

-118.300000,34.260000,43.000000,1510.000000,310.000000,809.000000,277.000000,3.599000,176500.000000

-117.810000,33.780000,27.000000,3589.000000,507.000000,1484.000000,495.000000,5.793400,270500.000000

-118.360000,33.820000,28.000000,67.000000,15.000000,49.000000,11.000000,6.135900,330000.000000

<_io.TextIOWrapper name='../../05_data/slides_data/california_housing_test.csv' mode='r' encoding='UTF-8'>


In [ ]:
with open('../../05_data/slides_data/california_housing_test.csv', 'r') as filehandle:
    #print(filehandle)
    print(filehandle.readlines())


In [ ]:
import csv
with open('../../05_data/slides_data/california_housing_test.csv', 'r') as filehandle:
    contents = csv.reader(filehandle)
    for row in contents:
        print(row)

In [53]:
import os
os.getcwd()

'c:\\Users\\hml\\DSI\\python\\06_cohort_three\\live_code'

In [54]:
os.listdir()

['30_april_2024-live_coding.ipynb']

In [58]:
cwd = os.getcwd()
fullpaths = []
for i in os.listdir():
    fullpaths.append(os.path.join(cwd, i))
print(fullpaths)

['c:\\Users\\hml\\DSI\\python\\06_cohort_three\\live_code\\30_april_2024-live_coding.ipynb']


In [59]:
# write() 
# writeline() # write each item in iterable printed without spaces

provinces = ['BC', 'AB', 'SK', 'MB', 'ON']
with open('provinces.txt', 'w') as provinces_file:
    provinces_file.writelines(provinces)

In [62]:
text = 'lavender is a small purple flower'
if os.path.exists('plants.txt'):
    print('plants.txt already exists')
else:
    with open('plants.txt', 'w') as file:
        file.write(text)

plants.txt a;lready exists


In [65]:
# OOP
# object is instant of a class
# objects have state (attributes) and behaviours (methods)
# attribute: data that belongs to a class

car_name = 'Taylor'
car_brand = 'Honda'
car_model = 'Civic'
car_vin = '1648246024'

class Car:
    # constructor
    # self is reference to the current instance of the class .i.e, object
    def __init__(self, name, brand, model, vin):
        self.name = name
        self.brand = brand
        self.model = model
        self.vin = vin

    def honk(self):
        print("beep beep beep")


anjali_car = Car('Anjali', 'Honda', 'Civic', '1231313')
anjali_car.honk()

    

beep beep beep


In [68]:
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age
        #self.address = address

    def greet(self):
        print('Hello, My name is', self.name)

anjali = Person('Anjali', 47)
kaylie = Person('Kaylie', 30)

anjali.greet()
kaylie.greet()

Hello, My name is Anjali
Hello, My name is Kaylie


In [79]:
class Dataset:
    '''Data values and methods to summarize them'''
    def __init__(self, values):
        self.values = values
        self.size = len(values)


    def unique(self):
        '''Return a list of unique values'''
        return list(set(self.values))


    def mean(self):
        '''Return the mean of all numeric values'''
        number = []
        for i in self.values:
            if type(i) is int or type(i) is float:
                number.append(i)

        return sum(number)/len(number)


my_dataset = Dataset([90, 70, 65, 'A', 90])
print(my_dataset.values)
print(my_dataset.size)
print(my_dataset.unique())
print(my_dataset.mean())
print(my_dataset.values)
    
        

[90, 70, 65, 'A', 90]
5
[65, 90, 'A', 70]
78.75
[90, 70, 65, 'A', 90]


In [84]:
import numpy as np


# 2D array i.e., matrix
a = np.array([[1, 2, 3], 
              [3, 2, 1]])


print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)


2
(2, 3)
6
int32


In [85]:
np.zeros([2,3,2])

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [86]:
np.ones_like(a)

array([[1, 1, 1],
       [1, 1, 1]])

In [87]:
np.arange(1, 10, 2) # 1 to 10 in steps of 2, not including 10

array([1, 3, 5, 7, 9])

In [88]:
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [89]:
np.random.randint(1, 10, (3, 4)) # 3 rows 4 cols

array([[3, 8, 2, 5],
       [8, 3, 2, 6],
       [3, 2, 5, 2]])

In [97]:
np.random.seed(100)
np.random.randint(1, 10, (3, 4)) # 3 rows 4 cols

array([[9, 9, 4, 8],
       [8, 1, 5, 3],
       [6, 3, 3, 3]])

In [98]:
print(np.repeat(10,5))


[10 10 10 10 10]


In [100]:
one_arr = np.array([1,2,3,4,5])

multidim_arr = np.repeat(one_arr, 5)
multidim_arr

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5,
       5, 5, 5])

In [101]:
multi_arr = np.tile(one_arr, (5, 1))
multi_arr

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [102]:
b = np.array([[5, 4, 3, 1 , 1],
                [10, 8, 4, 6, 3]
            ])
b.T

array([[ 5, 10],
       [ 4,  8],
       [ 3,  4],
       [ 1,  6],
       [ 1,  3]])

In [ ]:
b.reshape

b.flatten()

In [103]:
arr1 = np.array([5, 10, 15, 20])
arr1

array([ 5, 10, 15, 20])

In [104]:
arr2 = np.arange(5, 9)
arr2

array([5, 6, 7, 8])

In [105]:
arr1 - arr2

array([ 0,  4,  8, 12])

In [109]:
print(arr1 * 2)

[10 20 30 40]


In [110]:
arr1.sum()

50

In [111]:
arr1.mean()

12.5

In [112]:
np.median(arr1)

12.5

In [114]:
tens = np.arange(0, 120, 10).reshape(3,4)
tens

array([[  0,  10,  20,  30],
       [ 40,  50,  60,  70],
       [ 80,  90, 100, 110]])

In [115]:
horizontal = np.array([-5, -10, -15, -20])
horizontal

array([ -5, -10, -15, -20])

In [116]:
tens+horizontal # adding to all rows of tens

array([[-5,  0,  5, 10],
       [35, 40, 45, 50],
       [75, 80, 85, 90]])

In [117]:
 # axis = 0  column-wise operation i.e, down the rows
 # axis = 1  row-wise operation is across the columns
 tens

array([[  0,  10,  20,  30],
       [ 40,  50,  60,  70],
       [ 80,  90, 100, 110]])

In [118]:
tens.mean(axis=0) # (0+40+80)/3

array([40., 50., 60., 70.])

In [120]:
tens.mean(axis=1) # (0+10+20+30)/4

array([15., 55., 95.])

In [121]:
arr1

array([ 5, 10, 15, 20])

In [122]:
arr1[1]

10

In [123]:
arr1[1:3]

array([10, 15])

In [124]:
for i in arr1:
    print(i)

5
10
15
20


In [125]:
tens

array([[  0,  10,  20,  30],
       [ 40,  50,  60,  70],
       [ 80,  90, 100, 110]])

In [126]:
tens[1, 2]

60

In [127]:
tens[0]

array([40, 50, 60, 70])

In [128]:
tens[0:2, 0:3]

array([[ 0, 10, 20],
       [40, 50, 60]])

In [129]:
a = [3109, 202]
print(a)


[3109, 202]


[3109, 202]

In [131]:
matrix1 = np.random.randint(1, 11, 12).reshape(3,4)
matrix2 = matrix1
matrix1

array([[ 5,  5,  4,  8],
       [ 2,  2,  8,  8],
       [ 1,  3, 10, 10]])

In [132]:
matrix2

array([[ 5,  5,  4,  8],
       [ 2,  2,  8,  8],
       [ 1,  3, 10, 10]])

In [134]:
matrix3=matrix1.copy()
matrix3

array([[ 5,  5,  4,  8],
       [ 2,  2,  8,  8],
       [ 1,  3, 10, 10]])

In [135]:
matrix1[1] = [0,0,0,0]
matrix1

array([[ 5,  5,  4,  8],
       [ 0,  0,  0,  0],
       [ 1,  3, 10, 10]])

In [136]:
matrix2

array([[ 5,  5,  4,  8],
       [ 0,  0,  0,  0],
       [ 1,  3, 10, 10]])

In [137]:
matrix3

array([[ 5,  5,  4,  8],
       [ 2,  2,  8,  8],
       [ 1,  3, 10, 10]])